### This Notebook is used to inspect the data and understand what kind of data is stored in the different files

In [2]:
import numpy as np
from scipy.io import loadmat
import yaml

monkey -> minimodel format infos

In [3]:
data = np.load("monkeyv1_cadena_2019.npz")
print("monkey data: ",data.files)   # Liste aller Keys

monkey data:  ['images', 'responses', 'real_responses', 'test_images', 'test_responses', 'test_real_responses', 'train_idx', 'val_idx', 'subject_id', 'repetitions', 'image_ids']


minimodel -> experanto format infos

In [9]:
# ---- Spikes ----

data = np.load("FX20_nat60k_2023_09_29.npz")
#data = np.load("FX10_nat60k_2023_05_16.npz")
print("mice spikes data: ",data.files)   # Liste aller Keys
# sp: response of each neuron to each training (/ validation) image
# xpos: x cortical postion of each neuron
# ypos: y cortical postion of each neuron
# iplane: imaging plane the neuron is from 
# ss: ???
# istim_sp: indexes of the images in the image file corresponding to the stimuli used in "sp"
# istim_ss: indexes of the test images in the image file
# ss_all: responses of each neuron to each test image (500 images) to each repeat

mice spikes data:  ['sp', 'xpos', 'ypos', 'iplane', 'ss', 'istim_sp', 'istim_ss', 'ss_all']


In [10]:
print("data['iplane']: ", type(data['iplane']), ' shape: ', data['iplane'].shape, " min: " ,data['iplane'].min(), " max: " ,data['iplane'].max())

data['iplane']:  <class 'numpy.ndarray'>  shape:  (2746,)  min:  0  max:  1


In [4]:
# ---- Images -----
mat = loadmat("nat60k_text16.mat")
print(mat.keys())
print()

img = mat["img"]
istim = mat["istim"]
iorig = mat["iorig"]

print(type(img), ' img: ', img.shape, img.min(), img.max())
print(type(istim), ' istim: ', istim.shape, istim.min(), istim.max())
print(type(iorig), ' iorig: ', iorig.shape, iorig.min(), iorig.max())

istim = istim.squeeze()
iorig = iorig.squeeze()

print("istim: ", istim[:15])
print("iorig: ", iorig[:15])


dict_keys(['__header__', '__version__', '__globals__', 'img', 'istim', 'iorig'])

<class 'numpy.ndarray'>  img:  (66, 264, 68000) 0 255
<class 'numpy.ndarray'>  istim:  (1, 76800) 1.0 68000.0
<class 'numpy.ndarray'>  iorig:  (1, 68000) 1 1031
istim:  [13755. 22126. 11181. 18439.  8146. 11867.  4932. 14447.  4498. 13468.
 18991.  3845. 23236. 67995.  2095.]
iorig:  [  3 251  99 444 691 678 570 740 745 488 442 546 150 564 539]


sensorium format stuff (dont really need this. I use experanto)

In [5]:
# image stuff
data = np.load("nat30k_FX20_092923/data/images/0.npy")
print("sensorium img: ", data.shape)
print()

# meta stuff (statistics)
data_all = np.load("nat30k_FX20_092923/meta/statistics/images/all/std.npy")
data_frame = np.load("nat30k_FX20_092923/meta/statistics/images/stimulus_frame/std.npy")

print("data all: ", data_all)
print("data frame: ",data_frame)

sensorium img:  (1, 66, 130)

data all:  60.87348
data frame:  60.87348


experanto stuff

In [6]:
def load_meta(meta_path):
    with open(meta_path) as f:
        meta = yaml.load(f, Loader=yaml.SafeLoader)
    return meta

meta_resp = load_meta("/mnt/vast-nhr/projects/bthesis_cidas_richter/benjamin/experanto/examples/data/test_upsampling_without_hamming_30.0Hz/dynamic29515-10-12-Video-021a75e56847d574b9acbcc06c675055_30hz/responses/meta.yml")

In [7]:
# responses data.mem
path_to_mem = '/mnt/vast-nhr/projects/bthesis_cidas_richter/benjamin/experanto/examples/data/test_upsampling_without_hamming_30.0Hz/dynamic29515-10-12-Video-021a75e56847d574b9acbcc06c675055_30hz/responses/data.mem'

mm = np.memmap(path_to_mem,
                dtype=meta_resp["dtype"],
                mode="r",
                shape=(meta_resp["n_timestamps"], meta_resp["n_signals"]),
            )
print(mm.shape)     # n_timestamps * n_signals (226239*7863)
print()
print(type(mm), ' coords: ', mm.shape, mm.min(), mm.max())
print(mm[:10, :5])

(226239, 7863)



<class 'numpy.memmap'>  coords:  (226239, 7863) -2.3783784e-07 3097.847
[[5.6516662e-08 7.8008133e-09 4.7237330e-09 3.9485166e-09 4.3362305e-09]
 [5.3323351e-08 7.7624582e-09 4.0559214e-09 3.6069092e-09 4.3554422e-09]
 [5.0130041e-08 7.7241031e-09 3.3881096e-09 3.2653018e-09 4.3746535e-09]
 [4.6936730e-08 7.6857489e-09 2.7202980e-09 2.9236944e-09 4.3938653e-09]
 [4.4017661e-08 7.8827629e-09 2.1990036e-09 2.5959184e-09 4.3829109e-09]
 [4.1973220e-08 8.8304333e-09 2.1449917e-09 2.3122542e-09 4.2757486e-09]
 [3.9928775e-08 9.7781037e-09 2.0909798e-09 2.0285900e-09 4.1685864e-09]
 [3.7884334e-08 1.0725773e-08 2.0369681e-09 1.7449256e-09 4.0614241e-09]
 [3.5489862e-08 1.0872689e-08 1.9790083e-09 1.5852010e-09 3.9526142e-09]
 [3.2712233e-08 1.0143072e-08 1.9167268e-09 1.5611447e-09 3.8420009e-09]]


In [13]:
# response meta
path_to_coords = "/mnt/vast-nhr/projects/bthesis_cidas_richter/benjamin/experanto/examples/data/test_upsampling_without_hamming_30.0Hz/" \
    "dynamic29515-10-12-Video-021a75e56847d574b9acbcc06c675055_30hz/responses/meta/cell_motor_coordinates.npy"

coords = np.load(path_to_coords)
print(type(coords), ' coords: ', coords.shape, coords.min(), coords.max())
#print("coords example:", coords[:10])
print()


path_to_units = "/mnt/vast-nhr/projects/bthesis_cidas_richter/benjamin/experanto/examples/data/test_upsampling_without_hamming_30.0Hz/" \
    "dynamic29515-10-12-Video-021a75e56847d574b9acbcc06c675055_30hz/responses/meta/unit_ids.npy"

units = np.load(path_to_units)
print(type(units), ' units: ', units.shape, units.min(), units.max())
print("units example:", units[:20])
print()


path_to_means = "/mnt/vast-nhr/projects/bthesis_cidas_richter/benjamin/experanto/examples/data/test_upsampling_without_hamming_30.0Hz/" \
    "dynamic29515-10-12-Video-021a75e56847d574b9acbcc06c675055_30hz/responses/meta/means.npy"

means = np.load(path_to_means)
print(type(means), ' means: ', means.shape, means.min(), means.max())
print("means example:", means[0, :20])
print()


path_to_stds = "/mnt/vast-nhr/projects/bthesis_cidas_richter/benjamin/experanto/examples/data/test_upsampling_without_hamming_30.0Hz/" \
    "dynamic29515-10-12-Video-021a75e56847d574b9acbcc06c675055_30hz/responses/meta/stds.npy"

stds = np.load(path_to_stds)
print(type(stds), ' stds: ', stds.shape, stds.min(), stds.max())
print("stds example:", stds[0,:20])
print()

<class 'numpy.ndarray'>  coords:  (7863, 3) -1259 425

<class 'numpy.ndarray'>  units:  (7863,) 1 8736
units example: [ 1  3  4  6  7  8  9 10 11 12 14 15 16 17 19 20 21 22 24 25]

<class 'numpy.ndarray'>  means:  (1, 7863) 0.34729084 44.907436
means example: [1.0101055  1.3919626  1.6559083  1.2799321  0.87601894 1.3597481
 1.4360973  2.2154021  1.4847091  1.6313834  4.5415874  3.5730374
 2.2843792  5.556456   1.9431212  1.8679401  1.4543955  1.5915143
 1.6674546  1.3700268 ]

<class 'numpy.ndarray'>  stds:  (1, 7863) 1.6363426 118.30116
stds example: [ 3.6390064  4.395817   7.7685733  3.4157553  4.82132    4.2048125
  4.715402  11.372338   5.13376    7.3249125 17.757935  18.304998
  7.9372144 25.056507   7.9447684  6.451469   4.6372547  5.00186
  5.958239   4.4063673]



In [4]:
# screeen
path_to_timestamps = '/mnt/vast-nhr/projects/bthesis_cidas_richter/benjamin/experanto/examples/data/' \
    'test_upsampling_without_hamming_30.0Hz/dynamic29515-10-12-Video-021a75e56847d574b9acbcc06c675055_30hz/screen/timestamps.npy'

timestamps = np.load(path_to_timestamps)

print(type(timestamps), ' timestamps: ', timestamps.shape, timestamps.min(), timestamps.max())



path_to_means = "/mnt/vast-nhr/projects/bthesis_cidas_richter/benjamin/experanto/examples/" \
"data/test_upsampling_without_hamming_30.0Hz/dynamic29515-10-12-Video-021a75e56847d574b9acbcc06c675055_30hz/screen/meta/means.npy"

means = np.load(path_to_means)
print(type(means), ' means: ', means.shape, means.min(), means.max())
print("means example:", means[0, :20])
print()


path_to_stds = "/mnt/vast-nhr/projects/bthesis_cidas_richter/benjamin/experanto/examples/" \
"data/test_upsampling_without_hamming_30.0Hz/dynamic29515-10-12-Video-021a75e56847d574b9acbcc06c675055_30hz/screen/meta/stds.npy"

stds = np.load(path_to_stds)
print(type(stds), ' stds: ', stds.shape, stds.min(), stds.max())
print("stds example:", stds[0,:20])
print()

<class 'numpy.ndarray'>  timestamps:  (219541,) 1682534581.746954 1682541909.9080796
<class 'numpy.ndarray'>  means:  (1, 1) 80.459076 80.459076
means example: [80.459076]

<class 'numpy.ndarray'>  stds:  (1, 1) 57.486748 57.486748
stds example: [57.486748]



In [ ]:
import json

with open("/mnt/vast-nhr/projects/bthesis_cidas_richter/benjamin/minimodel/" \
"internship/data_experanto/nat30k_L1_A5_022723_experanto/screen/combined_meta.json", "r") as f:
    meta = json.load(f)

n_test = sum(1 for v in meta.values() if v.get("tier") == "test")
n_train = sum(1 for v in meta.values() if v.get("tier") == "train")
n_val = sum(1 for v in meta.values() if v.get("tier") == "validation")

print("train:", n_train, "val:", n_val, "test:", n_test, "total:", len(meta))


train: 24779 val: 0 test: 4907 total: 32440
