### This Notebook is used to inspect the data and understand what kind of data is stored in hte files

In [1]:
import numpy as np

monkey -> minimodel format infos

In [2]:
data = np.load("monkeyv1_cadena_2019.npz")
print("monkey data: ",data.files)   # Liste aller Keys

monkey data:  ['images', 'responses', 'real_responses', 'test_images', 'test_responses', 'test_real_responses', 'train_idx', 'val_idx', 'subject_id', 'repetitions', 'image_ids']


minimodel -> experanto format infos

In [3]:
#data = np.load("FX20_nat60k_2023_09_29.npz")
data = np.load("FX10_nat60k_2023_05_16.npz")
print("mice spikes data: ",data.files)   # Liste aller Keys
# sp: response of each neuron to each training (/ validation) image
# xpos: x cortical postion of each neuron
# ypos: y cortical postion of each neuron
# iplane: imaging plane the neuron is from 
# ss: ???
# istim_sp: indexes of the images in the image file corresponding to the stimuli used in "sp"
# istim_ss: indexes of the test images in the image file
# ss_all: responses of each neuron to each test image (500 images) to each repeat

mice spikes data:  ['sp', 'xpos', 'ypos', 'iplane', 'ss', 'istim_sp', 'istim_ss', 'ss_all']


sensorium format stuff

In [4]:
data = np.load("nat30k_FX20_092923/data/images/0.npy")
print("sensorium img: ", data.shape)   # Liste aller Keys

sensorium img:  (1, 66, 130)


experanto stuff

In [6]:
# responses data.mem
path_to_mem = '/mnt/vast-nhr/projects/bthesis_cidas_richter/benjamin/experanto/examples/data/test_upsampling_without_hamming_30.0Hz/dynamic29515-10-12-Video-021a75e56847d574b9acbcc06c675055_30hz/responses/data.mem'

mm = np.memmap(path_to_mem, dtype=np.float32, mode="r")
print(mm[:20])
print(mm.shape)     # n_signals * n_timestamps (7863*226239)
resized_mm = mm.reshape(7863, -1)
print(resized_mm.shape)
print(resized_mm[:5, :4])

[5.6516662e-08 7.8008133e-09 4.7237330e-09 3.9485166e-09 4.3362305e-09
 3.7114955e-08 1.7167004e-08 7.0196933e-09 6.0271299e-09 9.9741335e-09
 1.3524141e-07 1.9568093e-08 3.5835345e-08 4.9744497e-08 1.6269668e-08
 6.7225415e-08 7.1486337e-09 2.0254040e-08 1.3988490e-08 3.9526928e-09]
(1778917257,)
(7863, 226239)
[[5.6516662e-08 7.8008133e-09 4.7237330e-09 3.9485166e-09]
 [1.2240875e+00 4.4025124e+01 7.7899243e-10 7.5010276e+00]
 [3.4889755e-08 1.7608193e-09 6.2986709e-09 2.4511820e-07]
 [1.6582838e-07 6.2270686e-08 7.9580467e-08 1.5751562e-09]
 [1.8435908e-07 9.0749040e-08 2.6697720e-07 6.8775073e-08]]
